### ISSUE TITLE
TODO hunt

### ISSUE THREAD

**Issue by MattWindsor91** [UniversityRadioYork/ury-playd#29]
The [doxygen TODO list](http://universityradioyork.github.io/ury-playd/doxygen/todo.html) is rife with things that should be cleaned up for 0.1.0.
- [x] `CommandHandler::RunNullary`: Richer command results. 
- [x] `CommandHandler::RunUnary`: Richer command results. 
- [x] `IoReactor::NewConnection`: This isn't a great fit for the public interface of IoReactor - separate into a ConnectionPool class?
- [x] `IoReactor::RemoveConnection`: Rename sink?  This isn't a great fit for the public interface of IoReactor - separate into a ConnectionPool class?
- [x] `TcpResponseSink`: Rename to Connection? 
- [x] `TcpResponseSink::Close`: Roll into the destructor/use RAII?
